version: '3'
services:
    plex:
        image: linuxserver/plex
        container_name: plex
        volumes:
            - ./plex-config:/config
            - /tmp:/data/transcode
            # Media dirs injected here with override config
        network_mode: host
        restart: always
        environment:
            - VERSION=latest
            - TZ=Europe/Brussels
        ports:
            - 32400:32400

    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Brussels
          - USER=admin
          - PASS=admin
        volumes:
          - ./transmission-config:/config
          - /tmp/transmission/downloads:/downloads
          - /tmp/transmission/watch:/watch
        ports:
          - 51413:51413
          - 51413:51413/udp
        restart: unless-stopped

    bazarr:
        image: linuxserver/bazarr
        container_name: bazarr
        environment:
            - TZ=Europe/Brussels
        volumes:
            - ./bazarr-config:/config
            - ${MEDIA_DIR}/Movies:/movies
            - ${MEDIA_DIR}/TV Shows:/tv

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - ./radarr-config:/config
            - ${MEDIA_DIR}/Movies:/movies
            - /tmp/transmission/downloads:/downloads
        environment:
            - TZ=Europe/Brussels
        depends_on:
            - transmission

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
            - TZ=Europe/Brussels
        volumes:
            - ./sonarr-config:/config
            - ${MEDIA_DIR}/TV Shows:/tv
            - /tmp/transmission/downloads:/downloads
        depends_on:
            - transmission

    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 8080:8080
        depends_on:
            - transmission
            - plex
            - bazarr
            - radarr
            - sonarr
